[package]
name = "ven_os"
version = "0.1.0"
edition = "2021"
authors = ["Oskar Baran <oskar.baran.x@gmail.com>"]

[dependencies]
spin = "0.9.3"
volatile = "0.2.6"
x86_64 = "0.14.10"
linked_list_allocator = "0.9.0"
bootloader = { version = "0.9.23", features = ["map_physical_memory"]}

[dependencies.lazy_static]
features = ["spin_no_std"]